### ISSUE TITLE
Cannot find file ....ts.ktp.js

### ISSUE THREAD

**Issue by paynoattn** [sergeyt/karma-typescript-preprocessor#49]
Hello,

Thanks for this wonderful plugin. I cannot get it to work however. As you can see, I am running into an issue. I don't understand it, as I can see the file in my file system as the error appears, but then it shortly thereafter disappears.

```
$ karma start

START:
03 02 2016 16:08:07.454:ERROR [karma]: { [Error: ENOENT: no such file or directory, unlink '/Users/paynoattn/www/prototypes/jspm-ng1-template/www/app/app.spec.ts.ktp.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/Users/cpawlukiewicz/www/prototypes/jspm-ng1-template/www/app/app.spec.ts.ktp.js' }
Error: ENOENT: no such file or directory, unlink '/Users/cpawlukiewicz/www/prototypes/jspm-ng1-template/www/app/app.spec.ts.ktp.js'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:980:18)
    at /Users/cpawlukiewicz/www/prototypes/jspm-ng1-template/node_modules/karma-typescript-preprocessor/index.js:109:6
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Here's my karma.conf.js:
```
// Karma configuration

module.exports = function(config) {
  config.set({
     
    plugins: [
      require('karma-typescript-preprocessor'),
      require('karma-mocha-reporter'),
      require('karma-chrome-launcher'),
      require('karma-mocha'),
      require('karma-jspm'),
      require('karma-chai')
    ],
    
    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: [ 
      'jspm', 
      'mocha', 
      'chai'
    ],

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['mocha'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // list of files / patterns to load in the browser
    files: [],
    
    preprocessors: {
      'www/app/app.spec.ts': ['typescript'],
      'www/app/components/**/*.spec.ts': ['typescript']
    },
    
    typescriptPreprocessor: {
      typings: ['www/app/typings/**.*.d.ts'],
      options: {
        target: 'ES5',
        module: 'system'
      },
      transformPath: function(path) {
        return path.replace(/\.ts$/, '.js');
      }
    },

    jspm: {
      // Edit this to your needs
      config: 'www/config.js',
      loadFiles: ['www/app/**/*.spec.ts'],
      serveFiles: [
        'www/app/**/*.ts',
        'www/app/**/*.html',
        'www/app/**/*.scss'
      ]
    },
    
    proxies: {
      // '/jspm_packages': '/base/jspm_packages',
      // '/jspm.config.js': '/base/jspm.config.js'
    },

    // list of files to exclude
    exclude: [],

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

  });
};
```

**Comment by mmiszy** [comment]
Same problem here, have you found solution so far @paynoattn ?

**Comment by mmiszy** [comment]
I've managed to fix it. This problem occurs when you list the same file twice in your `files` in `karma.conf.js`. I had these entries which caused the problem:
```
files: [
    'app/**/*.module.ts',
    'app/**/*.ts'
]
```
which obviously included all `*.module.js` files twice. The solution was to change it to:
```
files: [
    'app/**/*.module.ts',
    'app/**/!(*.module).ts',
]
```

**Comment by sergeyt** [comment]
@raulramaya the preprocess is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options. Please retry again.
